platform :ios, "9.0"

source 'git@git.themindstudios.com:ios-frameworks/podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Jarvis_Example' do
    pod 'Jarvis', :path => '../'

  target 'Jarvis_Tests' do
    inherit! :search_paths

  end
end
